# Dockerfile
FROM python:3.14-slim@sha256:fb83750094b46fd6b8adaa80f66e2302ecbe45d513f6cece637a841e1025b4ca

RUN apt-get update \
  && apt-get install -y build-essential

# Install dependencies required for Tesseract
RUN apt-get update \
  && apt-get install tesseract-ocr -y \
  && rm -rf /var/lib/apt/lists/* \
  && tesseract -v

RUN apt-get update  \
&& apt-get install ffmpeg libsm6 libxext6  -y

RUN pip install poetry==2.3.2
